export const url = "http://192.168.0.104:10010"
const baseUrl = url + "/public"
export const engageMentUrl = baseUrl + "/engagement"

export const userUrl = baseUrl + "/user"
export const notificationUrl = baseUrl + "/notification"
export const postUrl = baseUrl + "/post"
export const reactionUrl = engageMentUrl + "/react"
export const commentUrl = engageMentUrl + "/comment"
export const messageUrl = baseUrl + "/message"